pygments:  true
markdown:  kramdown
permalink: pretty

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

css:
  theme: cosmo

name: Andrew Bunday
description: tech notes
