trigger:
- master

pool:
  vmImage:  'Ubuntu-16.04'

steps:
- checkout: self
  persistCredentials: true

# See: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-ruby-version?view=azdevops
- task: UseRubyVersion@0
  displayName: 'Use Ruby >= 2.5'

- script: 'gem install bundler'
  displayName: 'Install Bundler'

- script: 'bundle install'
  displayName: 'Install Jekyll and Dependencies'

- script: 'bundle exec jekyll build -d $(Build.ArtifactStagingDirectory)'
  displayName: 'Build Jekyll Static Site'

# - task: AmazonWebServices.aws-vsts-tools.S3Upload.S3Upload@1
#   displayName: 'S3 Upload: blog-andrewbunday'
#   inputs:
#     awsCredentials: andrewbunday.aws.s3
#     regionName: 'us-east-1'
#     bucketName: 'blog-andrewbunday'
#     sourceFolder: '$(Build.ArtifactStagingDirectory)'
#     filesAcl: 'public-read'
#     createBucket: true

