trigger:
- blog-source

pool:
  vmImage:  'Ubuntu-16.04'

steps:
- checkout: self
  persistCredentials: true

# See: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-ruby-version?view=azdevops
- task: UseRubyVersion@0
  displayName: 'Use Ruby >= 2.5'

- script: 'gem install bundler'
  displayName: 'Install Bundler'

- script: 'bundle install'
  displayName: 'Install Jekyll and Dependencies'

- script: 'bundle exec jekyll build -d $(Build.ArtifactStagingDirectory)'
  displayName: 'Build Jekyll Static Site'

- script: 'cd $(Build.Repository.LocalPath); git checkout master; git checkout -b azure-pipelines-build'
  displayName: 'Create Build Branch based on Master'

- script: >
    cd $(Build.Repository.LocalPath);
    git rm -rf .; git clean -fxd;
    touch .nojekyll;
    touch README.md;
    touch CNAME;
    echo "# My Blog" >> README.md;
    echo "andrewbunday.com" >> CNAME;
  displayName: 'Clean Build Branch'

- script: >
    git config --global user.email "andrew.bunday@gmail.com";
    git config --global user.name "Andrew Bunday";
  displayName: 'Configure Git User'

- script: 'cp -a $(Build.ArtifactStagingDirectory)/. $(Build.Repository.LocalPath)'
  displayName: 'Copy Artifact Files to Cleaned Build Branch'

- script: >
    cd $(Build.Repository.LocalPath);
    git add --all;
    git commit -m "Azure Pipelines: Updated site via $(Build.SourceVersion)";
  displayName: 'Create our Commit'

- script: >
    cd $(Build.Repository.LocalPath);
    git checkout master;
    git merge azure-pipelines-build;
    git branch -d azure-pipelines-build;
  displayName: 'Merge azure-pipelines-build into master'

- script: >
    cd $(Build.Repository.LocalPath);
    git push origin master;
  displayName: 'Push changes to remote'